# Generated by Django 5.2 on 2025-04-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='paper',
            field=models.CharField(default='Sample Paper', max_length=100),
            preserve_default=False,
        ),
    ]
