# Generated by Django 5.2 on 2025-04-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_question_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='paper',
            field=models.CharField(default='Sample Paper', max_length=100),
        ),
    ]
