# Generated by Django 5.2 on 2025-04-17 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_alter_question_paper'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
