# Generated by Django 5.2 on 2025-04-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classifier', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('module', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['paper'], name='classifier__paper_a0ab66_idx'), models.Index(fields=['module'], name='classifier__module_040747_idx'), models.Index(fields=['text'], name='classifier__text_9b3d85_idx')],
                'unique_together': {('paper', 'text')},
            },
        ),
    ]
