# Generated by Django 5.2 on 2025-04-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
