# Generated by Django 5.2 on 2025-04-18 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0008_clusteredquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusteredQuestion',
        ),
    ]
