# Generated by Django 5.2 on 2025-04-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_clusteredquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClusteredQuestion',
        ),
    ]
