# Generated by Django 5.2 on 2025-04-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0011_delete_clusteredquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusteredQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('module', models.IntegerField()),
                ('cluster_label', models.IntegerField()),
                ('difficulty', models.CharField(blank=True, max_length=20, null=True)),
                ('embedding', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
